name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Pruebas Unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pruebas
        run: pytest -v

  bandit-scan:
    name: SAST - Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Bandit
        run: pip install bandit

      - name: Ejecutar Bandit
        run: bandit -r . -x ./tests,./venv -ll -ii

  trivy-scan:
    name: Container Scan - Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagen local para escaneo
        run: docker build -t api-sre-daniel:scan .

      - name: Ejecutar Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'api-sre-daniel:scan'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

  deploy:
    name: Build y Despliegue
    needs: [test, bandit-scan, trivy-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: daniel444777/api-sre-daniel:latest

      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/proyecto-sre-daniel
            docker compose pull app
            docker compose up -d app
